name: melkio.blog
description: "Alessandro Melchiori's blog"
url: http://melkio.codiceplastico.com
markdown: redcarpet
pygments: true
auto: true
paginate: 5
paginate_path: "/page:num"
title: melkio.blog